### PR TITLE
Add Descriptor() to Message interface

### PR DESCRIPTION
**Pull request by RJPercival**

### CODE REVIEW

**Comment by LMMilewski** [comment]
This change would break everyone who implements the proto.Message interface. It not backwards compatible. I'm afraid that we can't accept this PR.

**Comment by RJPercival** [comment]
I expected as much, but thought I'd go for the simplest option first. Could we add another interface that aggregates this interface plus adds that method?

**Comment by LMMilewski** [comment]
Would that be different from descriptor.Message?
https://github.com/golang/protobuf/blob/master/descriptor/descriptor.go#L74

**Comment by RJPercival** [comment]
No, that's exactly what I was after, thanks! I had assumed it didn't already exist since I encountered people working around the lack of that interface, but I see that it's a relatively recent addition.

**Comment by RJPercival** [comment]
Ah there is one thing missing: an `EnumMessage` interface, e.g.
```
type EnumMessage interface {
  EnumDescriptor() ([]byte, []int)
}
```

**Comment by RJPercival** [comment]
What do you think of PR #302?

**Comment by alandonovan** [comment]
Has anyone published a coherent design for the addition of descriptors and
dynamic messages to the Go protobuf API?  It's clearly useful functionality
that a great many projects want, but my experience of two Google-internal
packages that add this functionality (dynamicproto and descpool) suggests
that a piecemeal approach can easily result in a large, cumbersome, and
concurrency-hostile API.

There are several use cases that ought to be considered together:
- loading FileDescriptorProto messages from a variety of sources such as
generated types linked into the application, .proto files in the file
system, and external databases.
- converting the message representation of descriptors ("DescriptorProtos")
into a cross-linked and indexed data structure ("Descriptors").
- instantiating messages of arbitrary types, not necessarily known at
compile time, from a map[string]interface{} and a Descriptor, and the
inverse operation of converting a message to a map.
- serializing/deserializing messages of arbitrary types to binary or text.

**Comment by RJPercival** [comment]
I don't have any involvement with either of those packages. This is actually the first change I've made to protobuf APIs, and I did so only because I encountered a number of Google-internal packages doing their own thing and saw that filling in this small gap in the descriptor API would be helpful.

However, from what I've seen so far, I certainly agree that a well thought-out design for where descriptors and dynamic messages should go from here is called for. I think issue #293 is probably the best place to have that discussion.

**Pull request closed without merging**
