### PR TITLE
Add tag flag to export message tag comments

### PR DESCRIPTION
**Pull request by lvht**
Some golang packages use struct tag to store infomation. For example, using [go-playground/validator](https://godoc.org/gopkg.in/go-playground/validator.v9), you can define a validate rule like this

```golang
type Test struct {
	Field `validate:"max=10,min=1"`
}
```

It will be great convenient if struct generated by protoc-gen-go according to proto has these tags.

This PR promotes a simple way to achieve this goal.

First, we introduce a so called **struct tag comment** like
```proto
message User {
    int32 uid = 1 // `validator:"gt=0"`
}
```

When we generate the *.pb.go, we enable the tag flag by `--go_out=tag=true:path`, wewill get 
```golang
type User struct {
    Uid int32 `protobuf:"varint,1,opt,name=uid,proto3" json:"mid,omitempty validator:gt=0"
}
```

So other packages could read the right struct tag.

----

There are some other solution like [gogo](https://github.com/gogo/protobuf) using the protobuf extension. But this PR is a more lightweight one.

### CODE REVIEW

**Comment by meling** [comment]
Issue #52 discuss various solutions that are related to this. Personally, I’m not in favor of adding validation tags to message fields, for reasons explained in one of my comments on #52. Especially not as comments in the proto file. I’m not sure what is the status of @dsnet’s proposal for `go_tags`, but seems like it has been put on hold, while the protobuf team resolves other issues.

**Comment by lvht** [comment]
@meling Thank you  for reply. This PR is not about the validation tags but generic tags. If it was accepted, any user defined tags in trailing comment can be added to the message struct tags. And it is the user's code's business to use these tags. And these does not have any meaning to the `protoc-gen-go`. And they are just comments in proto, there is no work to do for any util about proto.

**Comment by dsnet** [comment]
Hi, thanks for the PR, but we cannot accept this change. As @meling mentioned, the proposal to add this is #52. However, we are busy working on proto reflection and are not considering various generator extensions at this time.

If we add #52, it would have to be a proto option similar to what gogo/protobuf does. A magical comment that has special meaning in Go does not scale well with other languages and proto is intended to be a cross-language serialization technology that is mostly agnostic towards the target language.

**Comment by lvht** [comment]
@meling @dsnet 
> A magical comment that has special meaning in Go does not scale well with other languages

[golang/protobuf] is golang only. And the tag comment is golang only. And the tag comment is **just comment**, so other utils can not be confused.

**Comment by dsnet** [comment]
A comment is intended for human consumption and humans should be free to edit them as they please without accidentally breaking semantics. Machine interpretation of comments is a definite no-go. Proto options were invented to avoid hackery around comments.

**Comment by lvht** [comment]
@dsnet thank you

**Pull request closed without merging**
