### PR TITLE
jsonpb: fixing unmarshaling enum from int

### PR DESCRIPTION
**Pull request by goloveychuk**
Now it's unsafe, you can easily write any value and it will swallow.

### CODE REVIEW

**Comment by goloveychuk** [comment]
I signed it!

**Comment by goloveychuk** [comment]
I signed it!

**Comment by zombiezen** [comment]
Can you explain more what this does?  This changes the signature of an exported function for reasons that aren't clear to me.

**Comment by goloveychuk** [comment]
if unmarshalling old style enum value (represented by ints) - it wont be validated. You can unmarshall 
```json
{
     type: 32
}

while you having 
enum Type {
  a = 1;
  b = 2;
}
, and it will not return a error, so it's not secure to use this function

**Comment by dsymonds** [comment]
That's by design. The same thing happens when parsing from the binary format.

**Comment by dsymonds** [comment]
That's by design. The same thing happens when parsing from the binary format.

**Comment by dsymonds** [comment]
That's by design. The same thing happens when parsing from the binary format.

**Comment by goloveychuk** [comment]
@dsymonds 
by binary you mean serialised by protobuf or something like jsonb?
if first, there is a big difference between trusted services communication and function-helper unmarshaller from json.

**Comment by afking** [comment]
@goloveychuk I've made a similar change focusing on JSONPb. I think the function of marshaling enums should be `func UnmarshalJSONEnum(data []byte, enumName string) (int32, error)` as the maps are available by calling `proto.EnumValueMap(enumName)`.

**Comment by dsnet** [comment]
The JSON<->ProtoBuf spec allows unmarshaling an enum value that does not map to an known name. So this is working as intended.

**Pull request closed without merging**
