### PR TITLE
protoc-gen-go: remove deprecated function in grpc go

### PR DESCRIPTION
**Pull request by Chyroc**

### CODE REVIEW

**Comment by Chyroc** [comment]
this  https://github.com/grpc/grpc-go/pull/2027/files#diff-e2d91404d5609adc9273e4603f6ce67dR120  

and 

this  https://github.com/grpc/grpc-go/pull/2027/files#diff-fbfc8ce05aefe6707b98c99fa7317602R59

**Comment by dsnet** [comment]
\cc @dfawley to review.

@Chyroc, can you rebase against the `dev` branch? All new commits go there.

**Comment by dfawley** [comment]
LGTM, but does need to go on the `dev` branch.

**Comment by Chyroc** [comment]
What else do I need to do for this pr?

**Comment by dfawley** [comment]
I think you need a different PR to target `golang:dev` instead of `golang:master`.

**Pull request closed without merging**
