### PR TITLE
protoc-gen-go: Add -version flag to print version

### PR DESCRIPTION
**Pull request by stevenroose**
Fixes https://github.com/golang/protobuf/issues/598 and partially https://github.com/golang/protobuf/issues/524.

### CODE REVIEW

**Comment by dsnet** [comment]
Unfortunately, v1.1.0 has already been tagged, so we can't retroactively add this functionality without tagging another minor version (for which this is not worth a minor release on its own).

**Comment by dsnet** [comment]
Also, I'd rather not hard-code a version string as it is easy for that to get out of sync with the repository tag. Instead, I rather wait for proper versioning support to come with golang/go#24301. It's not just the version of `protoc-gen-go` you want to encode, but also all of its dependencies (namely the standard library), as that also affects the output.

**Comment by stevenroose** [comment]
> Unfortunately, v1.1.0 has already been tagged, so we can't retroactively add this functionality without tagging another minor version (for which this is not worth a minor release on its own).

Of course. I just added the latest version, so that it could be updated whenever a new release was made.

> Also, I'd rather not hard-code a version string as it is easy for that to get out of sync with the repository tag. Instead, I rather wait for proper versioning support to come with golang/go#24301. It's not just the version of protoc-gen-go you want to encode, but also all of its dependencies (namely the standard library), as that also affects the output.

I agree that an automatic way to include the version into the code would be safer. However I didn't know of any. Waiting for vgo might make sense, but could take more time.

**Comment by dsnet** [comment]
> Waiting for vgo might make sense, but could take more time.

It's certainly the correct path forward to fixing this. Russ is aiming to get vgo support into Go1.11, which is 3 months out. I'd rather wait for that.

Is there something that absolutely requires versioning info now? Or is this just a "nice to have"?

**Comment by stevenroose** [comment]
It's just cumbersome that in open-source project it's virtually impossible
to make changes to proto files and commit the respective changes to the
generated code, since a single update in any of the several used packages
(protoc, protoc-gen-go, protoc-gen-grpc-gateway, protoc-gen-swagger) will
change things that shouldn't be changed. So basically a PR to a proto file
has to be followed by a commit from the maintainer that has a consistent
setup.

**Comment by dsnet** [comment]
Closing this in favor of vgo support, which is moving along.

**Comment by stevenroose** [comment]
vgo doesn't really solve this. This is about external tools being able to determine the version of the executable.

**Comment by mvdan** [comment]
Maybe this should wait until the upcoming `go release` command. It sounds to me like exposing version information for executables is something it would do.

**Comment by stevenroose** [comment]
I'm ok with waiting until a good approach is figured out. But if it's closed, I feel like it'll be forgotten about soon :)

**Comment by mvdan** [comment]
Agreed. I've been struggling with the same problem in some projects of mine, and have temporarily added hard-coded version constants in a couple. I started watching this thread in the hopes that a better idea would come up :)

**Comment by dsnet** [comment]
I do care about having good versioning strings in protoc-gen-go, but I'm not fond of doing extra plumbing work for something that will probably be solved in the coming months. There are many other protobuf issues to address that is probably better to spend the limited time on.

**Comment by stevenroose** [comment]
I totally agree. But again, there's no harm in this issue being open and low priority.

**Comment by dsnet** [comment]
Perhaps, I'm misunderstanding something, but there is an open issue for this? #524

**Comment by stevenroose** [comment]
That issue is about logging the version used in the generated code.
> For now, I would be happy to just see items 1 and 2 start being encoded in the generated infolog.

That's different than having the executable log its version (like almost all GNU executables do, fwiw) so that tooling can check this version *before* generating new code.

**Comment by dsnet** [comment]
That issue is a superset of the functionality requested here. I still want #3 in that list (which is why that issue is still open). Once #524 is achievable, it is trivial to expose a command-line flag that exposes this information. I think we're spending time debating the same thing.

**Pull request closed without merging**
