### PR TITLE
Renamed README to README.md to enable github markdown rendering

### PR DESCRIPTION
**Pull request by byrnedo**

### CODE REVIEW

**Comment by byrnedo** [comment]
I signed it

**Comment by dsymonds** [comment]
It's not markdown. It's just a text file.

**Comment by byrnedo** [comment]
Renders pretty much as markdown. And personally that's much easier to read
when arriving at a github project.

**Comment by GeertJohan** [comment]
@byrnedo: Don't bother trying. @dsymonds is very stuborn. Been there done that.

**Comment by GeertJohan** [comment]
Hah! I was wrong! :smiley:
I see you pushed changes to make it markdown, @dsymonds. Nice!

**Pull request closed without merging**
