### PR TITLE
Generate field_mask.proto WKT.

### LINKED ISSUE #226: FieldMask is missing from ptypes directory.
I see https://github.com/google/protobuf/blob/master/src/google/protobuf/field_mask.proto is missing a go_package identifier and it does not appear in the ptypes directory with the other common proto files.

This file is needed for me to write the conformance tests in https://github.com/google/protobuf/tree/master/conformance and surely the FieldMask type would be needed in some cloud APIs.

### PR DESCRIPTION
**Pull request by tswast**
Upstream change is https://github.com/google/protobuf/pull/2058.

Fixes #226.

### CODE REVIEW

**Comment by dsymonds** [comment]
That doesn't look like the right output filename.

**Comment by tswast** [comment]
Oops. Yep, you're right. Fixed now.

**Comment by zombiezen** [comment]
Note that `FieldMask` already exists in [google.golang.org/genproto/protobuf](https://godoc.org/google.golang.org/genproto/protobuf).  See also #218.

**Comment by tswast** [comment]
@zombiezen Thanks for pointing that out. I'll read through that discussion. Possibly I'll need to change my upstream change to point to the genproto package name.

**Pull request closed without merging**
