### PR TITLE
jsonpb: improve error reporting

### PR DESCRIPTION
**Pull request by mwitkow**
This PR addresses the issue of:
https://github.com/golang/protobuf/issues/266

See the added test for the modification in error handling

### CODE REVIEW

**Comment by dsnet** [comment]
Adding error diagnostics sounds fine, but there is no reason to export the error type. Please unexport that.

**Comment by mwitkow** [comment]
I've rebased on latest master, and made the error struct private. @dsnet can you PTAL?

CC @io-ben @Helcaraxan

**Comment by dsnet** [comment]
Hi, thanks for working on this. Apologies for the long delay in reviewing. Can you actually rebase against the `dev` branch?

**Comment by mwitkow** [comment]
@dsnet done, it's now against `dev`. had to rewrite a bunch of commits.

**Comment by dsnet** [comment]
There are some test failures, fix?

**Comment by mwitkow** [comment]
😕 
```
--- FAIL: TestUnmarshalReturnsUsefulErrors (0.00s)
	jsonpb_test.go:1210: in UnknownFieldErrors expected error 
		'unparsable field Simple: fields [unknownOne unknownTwo] do not exist in set of known fields [oBool oInt32 oInt64 oUint32 oUint64 oSint32 oSint64 oFloat oDouble oString oBytes]'
		 but got 
		'unparsable field Simple: fields [unknownTwo unknownOne] do not exist in set of known fields [oBool oInt32 oInt64 oUint32 oUint64 oSint32 oSint64 oFloat oDouble oString oBytes]'
FAIL
FAIL	github.com/golang/protobuf/jsonpb	0.028s
```

and that's on the `1.x` run, which is using `1.10`, while the `1.10.x` test test run worked. 
How do I retrigger this run?

**Comment by healiha** [comment]
Would be great if we could finally have this improvement. You could `--amend --no-edit` your commit and force push to trigger a new build, although I'm not sure that's the best way to do it.

cc @dsnet

**Comment by base698** [comment]
Could also revert, then revert the revert and squash it.  I really need this feature as well...

**Comment by mwitkow** [comment]
rebased on top of latest `dev` and force pushed. Let's hope the Travis gods are benign ;)

**Comment by spenczar** [comment]
I'm interested in reviving this. @mwitkow, what's the status here? I can jump in.

**Comment by dsnet** [comment]
`jsonpb` has been completely re-written in v2, so all of this is probably moot.

See https://github.com/golang/protobuf/tree/api-v2/encoding/protojson

If the errors produced by v2 are still insufficient, it'd be good to improve the errors there.

**Comment by spenczar** [comment]
I haven't looked at the v2 errors yet, I'm not sure. I just got here from https://github.com/twitchtv/twirp/issues/148, through https://github.com/golang/protobuf/issues/266.

Is there a master issue for v2, or a targeted release date that I can track against?

**Comment by dsnet** [comment]
The closest thing to a "master" issue is #364, which was the primary reason for a v2.

There is no official release date, but we've been aspirationally trying to target a release by GopherCon 2019 (i.e., end of July). I say aspirational because there's still a number items to address.

**Comment by dsnet** [comment]
Closing as this is unlikely relevant in light of the v2 re-write.

**Pull request closed without merging**
