### PR TITLE
jsonpb: support omitempty for map and slice

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
PTAL?

**Comment by AkihiroSuda** [comment]
ping @dsnet @neild

**Comment by dsnet** [comment]
\cc @cybrcodr, jsonpb is your area ;)

**Comment by cybrcodr** [comment]
Fixed already in 7a211bcf3bce0e3f1d74f9894916e6f116ae83b4.

**Pull request closed without merging**
