### PR TITLE
do not allow files that cross package boundaries

### PR DESCRIPTION
**Pull request by jhump**
protoc-gen-go tries to disallow multiple files if they cross package boundaries -- it wants to be invoked for a single package at a time, and with all files for that package at the same time.

But it doesn't do a very good job checking for this condition. It simply verifies that the *package name* for all files is the same, but it does not check that all files emit code to the same package path (which is what Go really considers to be the identity of a package).

That means I can supply different files that have the same package name but live in different folders, and the generated code is simply wrong. Because it assumes they are the same package (including same package path), references from one to the other will result in code that uses naked symbol references (no package qualifier/alias) and also not produce an import statement.

So this change will cause the plugin to issue an error message if the files it produces would be in different Go packages.

### CODE REVIEW

**Comment by jhump** [comment]
@dsnet or @zombiezen: would either of you be the right person to take a look at this?

**Comment by jhump** [comment]
cc: @sanjaybv

**Comment by tamird** [comment]
@jhump I'd imagine this needs to go to the `dev` branch, since that's where all ongoing development is happening.

**Comment by jhump** [comment]
@tamird, yes, I know. I just never bothered rebasing this. It isn't urgent. I left it open as a reminder to myself to rebase it after dev finally gets merged to master.

**Comment by jhump** [comment]
I was pleasantly surprised that this rebased cleanly. But CLA bot got confused when I pushed the changes. Opening a different PR for this...

**Comment by jhump** [comment]
See #527 instead

**Pull request closed without merging**
