### PR TITLE
add no_omitempty option to remote omitempty label from generated struct

### PR DESCRIPTION
**Pull request by sparkthu**
#682

### CODE REVIEW

**Comment by dsnet** [comment]
Hi, thanks for the pull request, but we're going to decline. See my https://github.com/golang/protobuf/issues/682#issuecomment-414407450

**Comment by sparkthu** [comment]
@cybrcodr  I tried to use jsonpb, but the name style is totally different with json. We already have lots of code using underline name style instead of camel which is generated by jsonpb.
If there is any method to use under line name style in jsonpb, please let me know. Thank you.

**Comment by cybrcodr** [comment]
If you are using the original field name in the .proto file, you can set jsonpb.Marshaler.OrigName to true and that would use the original .proto field name which should be the same as the generated json tag name.

**Comment by sparkthu** [comment]
@cybrcodr Awsome! I love it. Thank you so much

**Pull request closed without merging**
