### PR TITLE
fix import_path parameter

### PR DESCRIPTION
**Pull request by mwitkow**
Fixes:
https://github.com/golang/protobuf/issues/63

### CODE REVIEW

**Comment by dsymonds** [comment]
Ignore that. Rogue bot.

**Comment by dsymonds** [comment]
Ignore that. Rogue bot.

**Comment by colinmarc** [comment]
This would also fix #167 for me.

**Comment by theobat** [comment]
Why is this not merged ? Fixes #63 for me, and it's not a huge change

**Comment by ashishnegi** [comment]
+1 . 
Any explanation for why this can not be merged will help community understand where the problem is.

**Comment by zombiezen** [comment]
[David's comment](https://github.com/golang/protobuf/pull/167#issuecomment-209226123) on #167 basically sums it up: the interplay between the existing import mechanisms is complicated and subtle.  We would like to make the whole mechanism simpler, which requires careful design.

**Comment by awalterschulze** [comment]
Is anyone busy doing this careful design?

**Comment by roadrunner** [comment]
Hello, any progress so far?

**Comment by zombiezen** [comment]
@neild is looking at it now, and we may have something soon.

**Comment by jacovieASAPP** [comment]
Where's this issue left off?

**Comment by neild** [comment]
(Sorry, I never noticed myself being tagged on this way back when.)

I don't understand this change. The `import_path` parameter is documented as "used as the package if no input files declare `go_package`". This PR modifies the import path of packages imported by the generated code, which is something completely different.

I admittedly don't see any reason to ever use the `import_path` parameter, since specifying the package name and import path as a `go_package` option is a strictly better alternative, but this seems to extend it in a surprising fashion inconsistent with its current behavior.

**Pull request closed without merging**
